name: ship_stability_calculator
description: "Offline Ship Stability and Draft Calculator for Seafarers"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  pdf: ^3.10.8
  printing: ^5.13.0
  path_provider: ^2.1.2
  share_plus: ^10.0.0
  file_picker: ^8.0.0
  excel: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "icon.png"

flutter:
  uses-material-design: true
  assets:
    - icon.png